== CloudForms + Satellite + Ansible OpenSCAP Playbooks

This repo contains two playbooks that leverage Satellite 6's built-in scanning capability.  For an OpenScap playbook that does not rely on Satellite 6, see the repo at  [ansible-openscap](https://github.com/jritenour/ansible-openscap).

These playbooks are designed to be ran within the context of Red Hat CloudForms, specifically using the built-in Ansible Automation.  With this, you can create a service catalog that references these playbooks in CloudForms, then create a custom button in CloudForms using Order_Ansible_Playbook as the request, and service_template_name/*name of service catalog item* as the attribute/value pair, then use those buttons to launch your scan & subsequent remediation against your CloudForms managed VMs.

=== openscap_scan.yml
Very straight forward, this is simply running the foreman_scap_client command against the first profile listed in the config file on the client.  Note that this playbook assumes the client has been registered in Satellite, has Puppet installed, and assigned a compliance profile in Satellite.  The report will then be available under the compliance reports section of CF.

=== openscap_remediation.yml
This playbook is intended to remediate the results of a SCAP scan.  Again, this assumes the client is registered to Satellite, and has been assigned a profile.

At this point, the remediation playbook will make use of Satellite's OpenSCAP profile, but due to limitations in the API with regard to the foreman scap client at the moment, it does not leverage the previously saved results.  Instead it does do a complete scan as part of the remediation.  I'll address this with a more elegant solution at some point in time.
