= Implementing Comprehensive Container and Kubernetes Security with OpenShift for Automated DevSecOps

=== [.underline]#Presenters/Lab Developers#:
*Lucy Kerner*, Senior Principal Security Global Technical Evangelist & Strategist, Red Hat

*Khary Mendez*, Senior Principal Consultant , Red Hat

*Andy Block*, Senior Principal Consultant, Red Hat

*Mike Surbey*, Specialist Solution Architect, Red Hat

*Justin Goldsmith*, Senior Architect, Red Hat


== Overview and Prerequisites:
In this hands-on lab, will cover the comprehensive container and kubernetes security capabilities available in Red Hat Openshift. Specifically:

* Host OS (Red Hat Core OS and Red Hat Enterprise Linux) security technologies
* Evaluating container content and sources for vulnerabilities
* Designing the build and CI/CD pipeline to proactively check container content and ensure content governance across the application lifecycle (image policy management and enforcement, image scanning, image signing)
* Certificate & Secrets management
* Implementing methods for controlling access to containers via authentication and authorization, and implement API management with Red Hat 3scale and single sign-on with Red Hat Single Sign-On.
* Red Hat OpenShift Container Platform security technologies (Security Context Constraints, RBAC, Network security, Istio, Storage security)
* Logging, Monitoring, & Audit.


This lab is geared towards systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to automate security and compliance across their heterogeneous infrastructure using one or more Red Hat Products.  The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA) or equivalent system administration skills. Knowledge of virtualization and basic linux scripting would also be helpful, but not required.

== Attendees, during this session, will learn:
* add more here
* How to build and automate security into your application by implementing DevSecOps at scale using Red Hat OpenShift Container Platform and several other tools, such as OWASP ZAP, SonarQube, Clair, and more to build a secure CI/CD application pipeline.


== Lab Environment:
Your entire lab environment is cloud hosted online and includes: Red Hat Ansible Automation, Red Hat Openshift Container Platform, and a workstation system which will have a public IP you can SSH into. You can get to all the listed Red Hat products and all your VMs from the workstation system.

You will each be given your own unique *GUID*, which you will use to access your own instance of these Red Hat products for your lab exercises.

Please do the lab exercises in order, starting with Lab 0.

== Table of Contents
* link:lab0-summit.adoc[Lab 0: Setup steps]
* link:lab1.adoc[Lab 1: OpenShift blocks rouge containers from running as privileged user]
* link:lab2.adoc[Lab 2: Implementing DevSecOps to Build and Automate Security into the Application in a Secure CI/CD Pipeline]
