== Lab 2: Host Hardening and Configuration Management

____
99% of the vulnerabilities exploited by the end of 2020 will continue to be ones known by security and IT professionals at the time of the incident.
____
-- https://www.gartner.com/smarterwithgartner/focus-on-the-biggest-security-threats-not-the-most-publicized/[Gartner]

With the pace of IT increasing, agile development pushing changes and new systems into the environment faster than ever before, and increasing complexity from new technologies such as public cloud, security gets harder and harder to keep up with. One of the best ways to protect ourselves is to simply do what we know we are supposed to do. In this lab we will use automation to do just that. 

In this lab, we will configure the following on our hosts to ensure we are are keeping up with general best practices.

* Deploy login banner
* Configure account password complexity
* Enable SELinux
* Harden SSH


. Login to Ansible Tower and select "Templates" from the navigation menu on the left. 

. Search or scroll through the templates to find the template named "LINUX / System Hardening". Then click the rocket ship icon to the right side of the window.

. You will be prompted for the hosts that you would like to configure. Enter `*rhel7_dev` into the text field. We will target our dev servers first. Click "Next" followed by "Launch" to begin the job.

. We will monitor the log as the configuration is checked and remediated on our systems. At the end we will see a Play Recap showing us how many changes were made on the systems.
