== Lab 7: Implementing DevSecOps to Build and Automate Security into the Application in a Secure CI/CD Pipeline

=== Goal of Lab 7

To exercise a devsecops pipeline, analyze result, and apply remediation.

=== Introduction

=== Lab 7.1 About the sample application

=== Lab 7.2 Logging into the environment

A number of tools have been installed and configured to support the devsecops pipeline. Each of these tools is running containerized within the OpenShift cluster.

==== Gogs
(description)

==== Jenkins
(description)

==== Nexus
(description)

==== SonarQube
(description)

==== Quay
(description)

Log in to each of the tools with the credentials shown below. Replace `{GUID}` with your lab cluster guid and `{user}` with your user id - e.g., `user`

* Gogs - http://gogs-ocp-workshop.apps.{GUID}.summit.opentlc.com
+
login: {user}
+
password: openshift

* Jenkins - https://jenkins-{user}.apps.{GUID}.summit.opentlc.com
+
login: {user}
+
password: openshift

* Nexus - http://nexus-ocp-workshop.apps.{GUID}.summit.opentlc.com
+
no login necessary

* Sonarqube - http://sonarqube-ocp-workshop.apps.{GUID}.summit.opentlc.com
+
no login necessary

* Quay - http://quayecosystem-quay-quay-enterprise.apps.{GUID}.summit.opentlc.com
+
login: admin
password: admin123



=== Lab 7.3 Explore the pipeline stages

TODO - Guided tour through each pipeline stage

=== Lab 7.4 Exercise an initial run through the pipeline

. Navigate back to the jenkins user interface https://jenkins-{user}.apps.{GUID}.summit.opentlc.com
+
. Click the folder label with your user id (e.g., user2)
+
. Click the pipeline (e.g., user2/user2-ecommerce-pipeline)
+
. Click the `Build with Parameters` link in the left menu
+
. Keep the default values and press the `Build` button
+
. Click the build label (e.g., #1) next to the build in the `Build History` pane on the left
+
. Click the `Console Output` link to monitor the build progress
+ 
. Once the build has completed successfully, click the `user#/user#-ecommerce-pipeline` link at the top of the display
+ 
. Navigate to each of the reports generated by the build on the left hand menu. Note the number of vulnerabilities found in the OpenSCAP Vulnerability report
* OpenSCAP Compliance Report
* OpenSCAP Vulnerability Report
* OpenSCAP ZAP Baseline Report
+
. Navigate to the SonarQube url http://sonarqube-ocp-workshop.apps.{GUID}.summit.opentlc.com Click on the `1` link above `Projects Analyzed`
+
. Note 3 vulnerabilites were found and that the unit test code coverage has been recorded. Click the Project and determine where the vulnerabilities are in the source code.
+
. Navigate to the nexus url http://nexus-ocp-workshop.apps.{GUID}.summit.opentlc.com, click `browse` then `maven-snapshots` Navigate the folder structure and verify your jar file exists within it.
+
. Navigate to the quay url http://quayecosystem-quay-quay-enterprise.apps.{GUID}.summit.opentlc.com, login as `admin` with the password `admin123`
+
. Navigate to the image tagged with your userid by clicking the `ecommerce` repository then click the tag icon on the left (second icon from the top)
+
. Click the image hash id then click the bug icon to see the vulnerabilities detected. Make a note of the number of vulnerabilities

=== Lab 7.5 Update the source code and base image

An old base images was used to build the application, we will update the base image to use a newer version. This will reduce the number of vulnerabilities that are detected. We will also update the source code to remove the vulnerabilities detected by SonarQube.

. Navigate to your source code repository in gogs http://gogs-ocp-workshop.apps.{GUID}.summit.opentlc.com
+
. Click on the `SecurityDemos` repository under `My Repositories`
+ 
. Click the `Dockerfile`
+
. Click the edit icon (small pencil) and change the image version from 1.0 to latest:
+
       FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
+
. Click the `Commit Changes` button
+
. Navigate back to the root of the SecurityDemos folder and clck down through the following folders src -> main -> java -> com -> baeldung -> ecommerce -> controller -> OrderController.java
+
. Edit the file and remove line 28, which has a hardcoded password. This password is not actually used by the applicaton so it is safe to remove
+
. Click the commit changes button
+ 
. Navigate back to Jenkins and start another build
+
. Once the build is complete review the reports, quay vulnerability scan and sonarqube to verify that the number of vulnerabilities has been reduced.

<<top>>

link:README.adoc#table-of-contents[ Table of Contents ] 