= Implementing Proactive Security and Compliance Automation and DevSecOps

=== [.underline]#Presenters/Lab Developers#:
*Lucy Kerner*, Director, Security Global Strategy and Evangelism, Red Hat^(R)^

*Will Tome*, Senior Solutions Architect, Red Hat

*Justin Lacey*, Architect, Red Hat

*Khary Mendez*, Principal Consultant , Red Hat

*Kevin Holmes*, Senior Solutions Architect, Red Hat

== Overview and Prerequisites:
In this hands-on lab, you’ll learn how to implement security and compliance automation at scale for the infrastructure, operations, and application across a hybrid environment, in a controlled way,  using a combination of various Red Hat products and technologies. Specifically, you will go through a series of exercises that will show you how, from a central place, you can: create and enforce control policies in an automated way, perform automated security scans and remediations for various different security profiles and security controls, do proactive security and automated risk management, implement automated web application hardening, and more. The goal of this lab is to introduce you to a variety of Red Hat products that can help you with proactive security and compliance automation across the infrastructure, operations, and application across a hybrid environment. We will demonstrate the power and flexibility of using either one or a combination of Red Hat products to help you with various security and compliance automation use cases.

This lab is geared towards systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to automate security and compliance across their heterogeneous infrastructure using one or more Red Hat Products.  The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA) or equivalent system administration skills. Knowledge of virtualization and basic linux scripting would also be helpful, but not required.

== Attendees, during this session, will learn:
* How to perform automated audit scans to quickly detect and automatically remediate security and compliance issues in a controlled way to ensure compliance against regulatory or custom profiles and for automated configuration compliance.
* How to implement infrastructure, security, and compliance as code.
* How to implement consistent and automated patch and configuration management.
* How to use Red Hat Satellite, OpenSCAP, and Red Hat Ansible Automation to automatically apply and enforce security policies
* How to use Red Hat Ansible Automation to proactively identify and remediate security threats at scale with automated risk management.
* How to have centralized management of your hybrid infrastructure for continuous security and monitoring.
* How to implement automated web application hardening.
* How to build and automate security into your application by implementing DevSecOps at scale using Red Hat OpenShift Container Platform and several other tools, such as OWASP ZAP, SonarQube, Clair, and more to build a secure CI/CD application pipeline.


== Lab Environment:
Your entire lab environment is cloud hosted online and includes: Red Hat Ansible Automation, Red Hat Openshift Container Platform, Red Hat Satellite, Red Hat Virtualization, Red Hat Openstack Platform, and a workstation system which will have a public IP you can SSH into. You can get to all the listed Red Hat products and all your VMs from the workstation system.

You will each be given your own unique *GUID*, which you will use to access your own instance of these Red Hat products for your lab exercises.

You must complete *Lab 0: Setup steps* and you must complete *Lab 4: Additional Automated Security Hardening of Host Systems* AFTER lab exercises #1-3.
Other than that, feel free to do the lab exercises in whatever order you'd like.

== Table of Contents
* link:lab0-workshop.adoc[Lab 0: Setup steps]
* link:lab1.adoc[Lab 1: Automated Scanning and Remediations of Host Systems for Vulnerabilities and Security Compliance]
* link:lab2.adoc[Lab 2: Enforcing Automated Compliance with Security Policies]
* link:lab3.adoc[Lab 3: Automated Patching of Host Systems]
* link:lab4.adoc[Lab 4: Additional Automated Security Hardening and Configuration Management of Host Systems]
* link:lab5.adoc[Lab 5: Automated Security Hardening of a Hacked Web Application]
* link:lab6.adoc[Lab 6: Implementing DevSecOps to Build and Automate Security into the Application in a Secure CI/CD Pipeline]
