---
- hosts: all
  become: yes

  tasks:
  - name: Set authorized key taken from file for root
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', 'id_rsa.pub') }}"

  - name: Install used packages
    package:
      name:
      - scap-security-guide
      - openscap-scanner
      - scap-workbench
      - xorg-x11-xauth
      - firefox
      state: present
    tags: setup

  - name: Install ansible dependency
    package:
      name:
      - python3-pip
      state: present
    tags: setup

  - name: Install ansible
    pip:
      name:
      - ansible
    tags: setup

  - name: Set SSH X Forwarding
    lineinfile:
      create: yes
      dest: /etc/ssh/sshd_config
      regexp: ^X11Forwarding
      line: "X11Forwarding yes"
    tags: setup

  - name: Remove produced artefacts
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/arf.xml
      - /tmp/report.html
      - /root/playbook.yml
    tags: rewind
