= Automate Your Security by Creating Custom Security Content


== [.underline]#Presenters/Lab Developers#:

*Matej Tyc*, Software Engineer and Tech Lead - Security Compliance, Red Hat

*Marek Haicman*, Senior QE and Product Owner - Security Compliance, Red Hat

*Lucy Kerner*, Security Global Technical Evangelist and Strategist, Red Hat

*Lukas Vrabec*, Senior Software Engineer - Security Controls, Red Hat

*Simo Sorce*, Senior Principal Software Engineer - RHEL Security, Red Hat


== [.underline]#Additional Lab Developers#:

*Jan Cerny*, Software Engineer - Security Compliance, Red Hat

*Watson Sato*, Software Engineer - Security Compliance, Red Hat


== Overview and Prerequisites:

This lab will introduce you to the https://github.com/ComplianceAsCode/content[ComplianceAsCode] project, the ultimate tool that composes content for automated security tools.
The project contains over one thousand of rules - elements of security policies.
Rules have descriptions, justification and reference to existing security standards.
They also have OVAL checks, Bash remediations and Ansible content to a varying degree.

In a series of scenarios, you will go through exercises as if you are a new system administrator who just joined a company who has not been historically good about practicing security.
As you have interest in improving the situation, you want to introduce a culture of security supported by automated evaluation and fast and  efficient problem resolution.
Luckily enough, the company uses RHEL, so in order to reach that goal, you are free to leverage the `ComplianceAsCode` project.
`ComplianceAsCode` allows you to produce a tailor-made security policy for your company with minimal effort, and the OpenSCAP ecosystem will do the scanning and suport for problem resolution.

This lab is geared towards systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to take advantage of the built-in security technologies in Red Hat Enterprise Linux.

The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA) or equivalent system administration skills.


== Attendees, during this session, will learn how to:

* Use the OpenSCAP scanner to scan systems and suggest or perform security fixes. 
* Navigate among existing rules, how to modify them and how to take advantage of parametrization.
* Create new security profiles, and populate them with existing rules.
* Create new rules from scratch, and add them to security profiles.
* Write OVAL checks with minimal effort, being confident about their correctness.
* Create pure Ansible content - scan and fix your system using pure Ansible.


== Lab Environment:

Your entire lab environment is hosted online and includes: Red Hat Enterprise Linux and Red Hat Ansible Automation.

You will each be given your own unique *GUID*, which you will use to access your own instance of these Red Hat products for your lab exercises.

Each lab exercise is independent from each other, so feel free to do the lab exercises in whatever order you'd like.


== Table of Contents
* link:lab0_setup.adoc[Lab exercise 0: Setup steps]
* link:lab1_introduction.adoc[Lab exercise 1: Introduction to the ComplianceAsCode framework]
* link:lab2_openscap.adoc[Lab exercise 2: Scanning Using OpenSCAP and Scap Workbench]
* link:lab3_profiles.adoc[Lab exercise 3: Create your own security policy from scratch]
* link:lab4_ansible.adoc[Lab exercise 4: Ansible-only content]
* link:lab5_oval.adoc[Lab exercise 5: The Art of OVAL Checks]
