== Lab 1: Provisioning a security compliant RHEL host in Red Hat Virtualization and Red Hat Openstack Platform

=== Goal of Lab 1
The goal of this lab is to show the ability for a user to click an order button in the service catalog of Red Hat CloudForms to execute specific custom defined services. Specifically, in this lab, a Red Hat CloudForms service will execute a specific Ansible Tower job template for your entire Ansible Tower inventory. You will also use the Red Hat CloudForms service catalog to see how you can create a security compliant host at provisioning time. This lab is another example of how you can automate security compliance at the push of a button.


=== Introduction
Red Hat CloudForms provides users the ability to create self-service catalogs.  Through the use of catalogs, Red Hat CloudForms provides support for executing free form automation as a service and also allow for multi-tier service provisioning to deploy layered workloads across hybrid environments. You can create customized dialogs that will give consumers of the services the ability to input just a few parameters and provision the entire service. In addition to using the native ruby language, free form automation workflows using the service catalog of Red Hat CloudForms can call Ansible Tower job templates as part of your automation workflow as well. All of this allows you to automate security compliance at the push of a button using Red Hat CloudForms and Ansible Tower.

=== Understanding how to use the Red Hat CloudForms service catalog to provision a security compliant host at the push of a button
=== Using the Red Hat CloudForms service catalog to order a service to execute an Ansible playbook against your entire Ansible Tower inventory



<<top>>

link:README.adoc#table-of-contents[ Table of Contents ] | link:lab2.adoc[ Lab 2 ]
