= Proactive Security Compliance Automation with CloudForms, Satellite, OpenSCAP, Insights, and Ansible Tower

=== [.underline]#Presenters#:
Lucy Kerner, Principal Technical Marketing Manager - Security, Red Hat

Patrick Rutledge, Principal Solutions Architect - GPTE, Red Hat

Nate Stephany, Senior Cloud Specialist Solutions Architect, Red Hat

Kevin Morey, Principal Cloud Specialist Solutions Architect, Red Hat

Will Nix, Principal Technical Marketing Manager - Red Hat Insights, Red Hat


== Abstract:
In this hands-on lab and demo environment, you will learn how to automate security compliance using a combination of Red Hat CloudForms, Red Hat Satellite, OpenSCAP, and Ansible Tower by Red Hat. Specifically, you will go through a series of exercises that will show you: how to use Red Hat CloudForms to create control policies, how to automate security scans and remediations using the OpenSCAP integration in Red Hat Satellite, how to utilize the data provided by Red Hat Insights for proactive security and automated risk management, how to use Ansible Tower by Red Hat for automated security remediations, and how to use Red Hat CloudForms as a central place for security compliance automation.

== Overview and Prerequisites:
The goal of this lab is to introduce you to a variety of Red Hat products that can help you with proactive security compliance automation. We will demonstrate the power and flexibility of using either one or a combination of Red Hat products, such as Red Hat Satellite, Ansible Tower by Red Hat, Red Hat Insights, and Red Hat CloudForms,  to help you with security compliance and automation.

This lab is geared towards systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to automate security compliance across their heterogeneous infrastructure using one or more Red Hat Products.  The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA) or equivalent system administration skills. Knowledge of virtualization and basic linux scripting would also be helpful, but not required.

== Table of Contents
* link:lab0.adoc[Lab 0]
