== Lab 9: How to use GNU Privacy Guard (GPG) to identify yourself and encrypt your communications

=== Goal of Lab:
GNU Privacy Guard (GPG) is a cryptographic software package that is included in your Red Hat Linux subscription.  It can be used to identify yourself and encrypt your communications.  It can also be used to encrypt files at rest, which will be the focus of this exercise.  This will allow you to become comfortable with some the basics of GPG, after which point, you can delve further into the documentation to use more advanced features, such as signing RPM packages, or encrypting email communications.

The documentation can be found at:

https://gnupg.org/index.html

There are various tools that you can use to manage GPG on your system, graphical as well as command line.  We will use the command line tools for the steps in this exercise.

=== Logon to Your System:
. Logon to servera.example.com as *root* using *r3dh4t1!* as your password.

[source]
[lab-user@workstation-GUID ~]$ ssh root@servera.example.com
[root@servera ~]#

. Rather than use the root account, let’s create a new user account and assign it a password and do our work from within that scope.  From the command line, perform the following:
+
[source]
useradd student
passwd student

Once that account is established, logout as root and log back in as your new user.

=== Generating a New Key Pair
Once you have created a new key pair, you can export these keys to identify yourself to the rest of the world, or simply use it locally to encrypt your files at rest.   To generate your new key pair, login as your new user and enter the following command:
+
[source]
gpg2 --gen-key

You will be asked to provide the following information:

* Key Type - RSA is the default, but you have options
* Key Size - 2048 bits is usually sufficient
* Expiration - no expiration if generally fine for local encryption
* User ID: this will be your name and email address
* Passphrase: make this hard enough to protect against attacks

At this point you system will start generating the key pair.  You will be asked to assist in helping generate entropy by moving your mouse or typing random keystrokes.  Eventually it will complete and you will have your new key pair that you can now use.  The output will list your key and your fingerprint.  If you wish to view them at a later time, run the following commands:

+
[source]
gpg2 --list-keys [student]
gpg2 --fingerprint [student]

The contents of you key is stored in your home directory at .gnupg.  Even if someone were to compromise your computer, this would be of no use to them as long as your passphrase is sufficiently hard to crack.  That said, always maintain a backup.

=== Encrypting Documents
In this step we will show you how to encrypt and un-encrypt a document for private use.  We will start by creating a document with sensitive information.

. Please type the following:

+
[source]
echo “I love Red Hat!” > sensitive.txt

. To verify that you can read the document in it’s un-encrypted format, type the following:

+
[source]
cat sensitive.txt

. Now we can encrypt the file by typing the following command:
+
[source]
gpg2 -e sensitive.txt

. You will be asked to enter the ID you entered when you created your key, followed by a carraige return to complete the task.  Note that you now have a new file entitled sensitive.txt.gpg.  The .gpg extension indicated that it is a file that has been encrypted with a GPG key.  Verify the encryption by typing the following:
+
[source]
cat sensitive.txt.gpg

. You will see that the output is encrypted and cannot be read.  You can read this file by typing the following command, which will prompt you for the passphrase you created earlier:
+
[source]
gpg2 -d sensitive.txt.gpg

. Next we will delete the original file and then recreate it in its un-encrypted format from the encrypted file:
+
[source]
rm sensitive.txt
gpg2 sensitive.txt.gpg
ls -l sensitive*

. Note, that you now have a new copy of your original file.  Also note, that during an active session you may not be asked to provide a passphrase within a period of time.  You can modifiy the duration of the cache.  I would recommend reviewing the GPG documentation at the link provided earlier.

=== Summary
This exercise demonstrated a simple use case in which you encrypted personal documents.  You can build on what you have learned by using your key to sign documents, encrypt email communications. sign rpm packages, or simply share documents with a colleague.

<<top>>

link:README.adoc#table-of-contents[ Table of Contents ] | link:lab10_firewalld.adoc[ Lab 10: Firewalld ]
