= How to set up a system with SELinux confined users

== Introduction

In Red Hat Enterprise Linux, Linux users are mapped to the SELinux unconfined_u user by default. All processes run by unconfined_u are in the unconfined_t domain. This means that users can access across the system within the limits of the standard Linux DAC policy. However, a number of confined SELinux users are available in Red Hat Enterprise Linux. This means that users can be restricted to limited set of capabilities. Each Linux user is mapped to an SELinux user using SELinux policy, allowing Linux users to inherit the restrictions placed on SELinux users.    

== User Story

As an enterprise administrator I want my systems to follow the STIG rule V-71971 so that my system will be fully confined without unconfined users.
I want one administrator user who can become root and manage the system, and other users to be limited so that they can't become root.

== Implementation

The lab exercise is divided to three steps:

. Confine regular Linux users
. Confine Linux root users

== Confine regular Linux users

All actions are performed on the _selinux2_ host which is RHEL-7.6 Beta installation. 

Log into the _selinux2_ host system:

    # ssh root@selinux2

Linux users can be assigned to SELinux users using semanage login tool. By default users are mapped to _unconfined_u_:

    # semanage login -l

=== Change the default mapping

In order to change mapping all Linux users we need to modify the record with __default__ which represents all users without explicit mapping. 

_system_u_ is a special user used only for system processes and in the future will not be listed.

    # semanage login -m -s user_u -r s0 __default__
    # semanage login -l

=== Add a test user

After this when users (not root) will log in, their processes will run _user_t_ domain. Every user session but root will run with _user_t_:


    # adduser user42
    # passwd user42
    …

    # ssh user42@localhost
    user42@localhost's password:

    [user42@localhost ~]$ id -Z
    user_u:user_r:user_t:s0

    [user42@localhost ~]$ ps axZ
    LABEL                     PID TTY    STAT  TIME COMMAND
    -                           1 ?      Ss    0:00 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
    user_u:user_r:user_t:s0  2780 ?      S     0:00 sshd: user42@pts/1
    user_u:user_r:user_t:s0  2781 pts/1  Ss    0:00 -bash
    user_u:user_r:user_t:s0  2808 pts/1  R+    0:00 ps axZ
    # exit

Now we can try if the user can become root. We need to add following line:

    #  visudo -f /etc/sudoers.d/administrators
    # grep user42 /etc/sudoers.d/administrators
    user42  ALL=(ALL)       NOPASSWD: ALL

    # ssh user42@localhost
    user42@localhost's password:

    [user42@localhost ~]$ sudo -i
    sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
    sudo: no valid sudoers sources found, quitting
    sudo: setresuid() [0, 0, 0] -> [1001, -1, -1]: Operation not permitted
    sudo: unable to initialize policy plugin

And the same attempt in permissive mode.

    [user42@localhost ~]$ exit
    # id -Z
    unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
    # setenforce 0
    # ssh user42@localhost
    user42@localhost's password:

    [user42@localhost ~]$ sudo -i
    # id
    uid=0(root) gid=0(root) groups=0(root) context=user_u:user_r:user_t:s0
    [root@localhost ~]# id -Z
    User_u:user_r:user_t:s0
    [root@localhost ~]# exit
    [user42@localhost ~]$ exit
    [root@localhost ~]# setenforce 1

Since in permissive mode SELinux denials are not enforced, user42 can become root but we can see that the context stayed _user_t_ and didn't change to _unconfined_t_.

== Confined Administrator

There are two basic methods how to confine administator user.
Administrator can be directly mapped to sysadm_u SELinux user so that when such user logs in, the session will be run with _sysadm_t_ domain. In this case you need to enable ssh_sysadm_login SELinux boolean in order to allow users assigned sysadm_u to login using ssh.

    # semanage user -m -R "sysadm_r secadm_r" sysadm_u
    # adduser -G wheel -Z sysadm_u admin1
    # passwd admin1

    # semanage login -l | grep admin
    admin1               sysadm_u             s0-s0:c0.c1023       *


    # setsebool -P ssh_sysadm_login on


    # ssh admin1@localhost


    [admin1@localhost ~]$ id -Z
    sysadm_u:sysadm_r:sysadm_t:s0-s0:c0.c1023


    $ sudo -i
    [sudo] password for admin1:


    [root@localhost ~]# id -Z
    sysadm_u:sysadm_r:sysadm_t:s0-s0:c0.c1023


    [root@localhost ~]# systemctl restart sshd
    [root@localhost ~]# exit
    [admin1@localhost ~]# exit

The other way is to assign u administer users to _staff_u_ and configure sudo so that particular users can gain SELinux administrator role.

    # adduser -G wheel -Z staff_u admin2
    # passwd admin2
    # semanage login -l | grep admin
    admin1               sysadm_u             s0-s0:c0.c1023       *
    admin2               staff_u              s0-s0:c0.c1023       *


    # ssh admin2@localhost
    [admin2@localhost ~]$ id -Z
    staff_u:staff_r:staff_t:s0-s0:c0.c1023


    [admin2@centos7 ~]$ sudo -i
    [sudo] password for admin2:
    -bash: /root/.bash_profile: Permission denied
    -bash-4.2# id -Z
    staff_u:staff_r:staff_t:s0-s0:c0.c1023
    -bash-4.2# systemctl restart sshd
    Failed to restart sshd.service: Access denied
    See system logs and 'systemctl status sshd.service' for details.
    -bash-4.2# exit
    [admin2@centos7 ~]$ exit

To allow admin2 user to gain SELinux administrator role you need to add the following rule to sudoers.

    # visudo -f /etc/sudoers.d/administrators

Append following line to end of file:

    admin2  ALL=(ALL)  TYPE=sysadm_t ROLE=sysadm_r    ALL
    admin2  ALL=(ALL)  TYPE=secadm_t ROLE=secadm_r /usr/sbin/semanage,/usr/sbin/semodule

Admin2 can gain administrator role using sudo now.

    # ssh admin2@localhost
    [admin2@centos7 ~]$ sudo -i
    [sudo] password for admin2:


    [root@centos7 ~]# id -Z
    staff_u:sysadm_r:sysadm_t:s0-s0:c0.c1023


    [root@centos7 ~]# systemctl restart sshd
    [root@centos7 ~]#

