= Lab X: USBGuard Demo

== Configuration

This demo is based on a RHEL 7.5 Beta VM residing inside the Summit lab environment. KVM/libvirt is used to create and manage virtual machine inside the RHEL 7.5 VM.

USBGuard RHEL 7.4 VM:    _usbguard-demo_

*Important*: All steps in the _Configuration_ section have been already performed in the Summit lab environment and it is mentioned from an informative purpose. You can read them to get familiar with the setup. Start the practical part of the lab with the _Demonstration_ section of this lab.

=== Create the virtual machine

First configure virt-builder to use our internal RHEL images:

	# cat -> /etc/virt-builder/repos.d/rhel.conf <<EOF
	[rhel]
	uri=http://file.rdu.redhat.com/~rjones/builder/index.asc
	EOF

Then create the usbguard VM image using virt-builder (from libguestfs-tools-c package):

	> virt-builder rhel-7.4 -o usbguard-rhel-7.4-vm.qcow2 --format qcow2 --root-password password:redhat --update --install usbguard --install usbguard-tools --install usbutils --install udisks2

=== Setup the virtual machine

First transfer the usbguard VM image to the host VM.

Then ssh into the host VM and install the usbguard VM using virt-install (from virt-install package):

	# virt-install --name usbguard-demo --memory 512 --disk /var/lib/libvirt/images/usbguard-rhel-7.4-vm.qcow2 --graphics none --os-variant rhel7.4 --import

Stop the VM if it is running using virsh:

	# virsh list
	 Id    Name                           State
	----------------------------------------------------
	 1     usbguard-demo                  running


	# virsh destroy 1


=== Simulating hot plugging with virsh

Instead of configuring hot plug pass-through, it is easier to attach and detach USB drives to the virtual machine via _virsh_.  
XML file for virtual USB disk (usb-disk.xml):

	# cat usb-disk.xml
	<disk type='file' device='disk'>
   	 <driver name='qemu' type='raw' cache='none'/>
   	 <source file='/root/usb-disk.img'/>
   	 <target dev='vdd' bus='usb'/>
   	 <serial>RED</serial>
	</disk>

Create as many XML files as you want to have available drives with unique serial values. Note that you have to create the file referenced in the _<source>_ file attribute:

	# dd if=/dev/zero of=/root/usb-disk.img bs=1M count=32

The same steps are neede to create another USB disk used in this lab (usb-disk-2.xml). 

	# cat usb-disk-2.xml
	<disk type='file' device='disk'>
   	 <driver name='qemu' type='raw' cache='none'/>
   	 <source file='/root/usb-disk-2.img'/>
   	 <target dev='vdd' bus='usb'/>
   	 <serial>RED</serial>
	</disk>

	# dd if=/dev/zero of=/root/usb-disk-2.img bs=1M count=32

From the host VM you can simulate USB disk hotplug using virsh:

	# virsh attach-device usbguard-demo usb-disk.xml
	# virsh detach-device usbguard-demo usb-disk.xml

=== Setup USBGuard demo

The usbguard-demo VM contains pre-installed (by virt-builder) _usbguard_, _usbguard-tools_, _usbutils_ and _udisks2_ packages. The VM is running RHEL 7.4.

You can also use _udisksctl_ to show the available status of a USB drive in the examples instead of ‘lsblk’.  Where you see ‘lsblk’ in the guide, you can replace it with ‘udisksctl status’

Output comparison with allowed drive attached as _sda_:

	[root@usbguard-demo ~]# lsblk 
	NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
	sda      8:0    1  7.6G  0 disk 
	└─sda1   8:1    1  7.6G  0 part 
	vda    253:0    0    6G  0 disk 
	├─vda1 253:1    0    1G  0 part /boot
	├─vda2 253:2    0  615M  0 part [SWAP]
	└─vda3 253:3    0  4.4G  0 part /

	[root@usbguard-demo ~]# udisksctl status
	MODEL                     REVISION  SERIAL                        DEVICE
	--------------------------------------------------------------------------
	VirtIO Disk                                                          vda     
	SMI USB DISK              1100      SMI_USB_DISK-0:0        sda   

== Demonstration

Most steps are taken on the _usbguard demo_ virtual machine.  Adding and removing USB drives are done from the RHEL 7.5 Beta host VM - _usbguard.example.com_ .  This demo is highly command line driven, you can expand the demo to show more or less context around the actions taken.

Start the _usbguard-demo_ VM and connect to its console using:

	# hostname 
	usbguard.example.com

	# virsh start usbguard-demo
	# virsh console usbguard-demo
	Connected to domain usbguard-demo
	Escape character is ^]
	<ENTER>

	Red Hat Enterprise Linux Server 7.4 (Maipo)
	Kernel 3.10.0-693.el7.x86_64 on an x86_64

	localhost login:

Login as root using the password “redhat”.

=== USBGuard dynamic policy

Generate a base policy without any external devices attached.  This will allow the USB hubs and any other system level USB devices. The default action of USBGuard is to block any device not in the policy.

On usbguard-demo:

	# usbguard generate-policy -X
	# usbguard generate-policy -X > /etc/usbguard/rules.conf
	# systemctl enable usbguard --now
	# usbguard list-rules

Attach a USB drive to show what blocking means.  You can see the device in the USB tree, but it will not be available to be mounted.  The native usbguard tools will see the device and show the current action for it.

On host:

	# hostname
	usbguard.example.com

	# sudo virsh attach-device usbguard-demo usb-disk.xml

On usbguard-demo:

	# lsusb
	# lsblk
	# usbguard list-devices
	# usbguard list-devices --blocked

USBGuard allows admins to dynamically change the action on a specific device.  Show changing the policy on the USB drive and show that it becomes available for mounting when allowed.

On usbguard-demo:

	# usbguard list-devices
	# usbguard allow-device <ID>
	# usbguard list-devices
	# usbguard list-rules
	# lsblk

	# usbguard block-device <ID>
	# usbguard list-devices
	# lsblk

While dynamic block and allow is a very nice feature, these don’t survive a reboot.  The more powerful use comes from setting permanent policy in /etc/usbguard/rules.conf.

=== USBGuard permanent policy

The same dynamic command can create a permanent entry in combination with an immediate action using the ‘-p’ option.

On usbguard-demo:

	# usbguard allow-device -p <ID>
	# usbguard list-rules
	# cat /etc/usbguard/rules.conf

	# usbguard block-device -p <ID>
	# usbguard list-rules

=== USBGuard policy for multiple USB devices

OPTIONAL: The policy has been created for a very specific device.  Test that other USB devices will be blocked by adding a second USB drive from the host.  The _hash_ is calculated by USBGuard to identify individual devices.


On host :

	# virsh attach-device usbguard-demo usb-disk-2.xml

On usbguard-demo:

	# usbguard list-devices


=== Reject USB device(s) via USBGuard policy

Policies built to allow or block specific devices is very good where devices can be vetted and identified.  For other environments, more flexible rules based on device characteristics are useful.  Blocking devices in this environment may not be strict enough.  We can also reject devices, which will tell the kernel to remove the device from the system.  A rejected device will not be visible in _lsus_’, _usbguard list-devices_, or in the _/sys/bus/usb/devices_ tree. Generate a new base policy with the ‘reject’ action.

On host:

	# virsh detach-device usbguard-demo usb-disk.xml

On usbguard-demo:

	# systemctl stop usbguard
	# usbguard generate-policy -X -t reject > /etc/usbguard/rules.conf
	# cat /etc/usbguard/rules.conf
	# systemctl start usbguard
	# usbguard list-rules

Show how the _reject_ action differs from the _block_ action. The journal records the kernel action as well as the USBguard action. You can highlight the entries in the logs.

On host:

	# sudo virsh attach-device usbguard-demo usb-disk.xml

On usbguard-demo:

	# lsusb
	# lsblk
	# journalctl -b -e

=== Reset VM setup

	# virsh detach-device usbguard-demo usb-disk.xml
	# virsh detach-device usbguard-demo usb-disk-2.xml
	# rm /etc/usbguard/rules.conf
