---
- name: Install openssh server
  win_chocolatey:
    name: openssh
    params: /SSHServerFeature
    state: present

- name: Enable sshd
  win_service:
    name: SSHD
    start_mode: auto
    state: started
