---
# keyword is arbitrary and use in zabbix Actions to filter hosts that
# will be authorized to auto-register
zabbix_auto_registration_keyword: OCP Host
# hostname that appears in Zabbix.
zabbix_hostname: "{% if repo_version is defined %} OCP {{ repo_version }} {% endif %}{{ guid }} - {{ ansible_hostname }}"
zabbix_host: 23.246.247.58
