---
- name: Import default destroy playbook
  import_playbook: ../../cloud_providers/{{cloud_provider}}_destroy_env.yml

#- name: Unsubscribe
#  hosts: all
#  become: true
#  ignore_errors: true
#  tasks:
#    - shell: "subscription-manager unsubscribe"
