---
#
# AgnosticD vars configuration file
# 
# Summit 2020 Hands-On Lab:
# RHEL Security
#
# This configuration deploys a RHEL8 bastion and 1 node.
#
# Rev. 2/6/2020
#
# Usage:
#
# mkdir <some-dir>
# cd <some-dir>
# git clone https://github.com/RedHatDemos/SecurityDemos/tree/master/2020Labs/RHELSecurity/ansible/agnosticd
# cd angnosticd/ansible
# ansible-playbook main.yml -e @../../../myconfigs/sample_vars.yml -e @/Users/lkerner/.aws/credentials
#

#
# Destroy the config.
#
# ansible-playbook -e @../../../myconfigs/sample_vars.yml -e @/Users/lkerner/.aws/opentlc-aws-creds.yaml  configs/rhel-security/destroy_env.yml
#
env_type: rhel-security       # Name of config to deploy
output_dir: /tmp/workdir                # Writable working scratch directory
email: lkerner@redhat.com              # User info for notifications

#guid: 5e2a                                    # Your Global UNIQUE Identifier
guid: lkerner
subdomain_base_suffix: .sandbox663.opentlc.com   # Your domain used with guid in FQDN

# Satellite 
repo_method: satellite
satellite_url: labsat.opentlc.com
satellite_activationkey: rhel8-summit
satellite_org: Red_Hat_GPTE_Labs
use_content_view: true

# Cloud specfic (AWS) settings.
cloud_provider: ec2                     # Which AgnosticD Cloud Provider to use
aws_region: us-east-1                   # AWS Region to deploy in
HostedZoneId: Z2BBY0O4PIUKAT             # You will need to change this
key_name: id_rsa              # Keyname must exist in AWS
bastion_instance_image: RHEL81
node_instance_image: RHEL81
remote_user: ec2-user                   # Needed to workaround some bug.

#
# Security Groups
#
security_groups:
  - name: BastionSG
    rules:
      - name: BasSSHPublic
        description: "SSH public"
        from_port: 22
        to_port: 22
        protocol: tcp
        cidr: "0.0.0.0/0"
        rule_type: Ingress

      - name: Bas8080Public
        description: "8080 public"
        from_port: 8080
        to_port: 8080
        protocol: tcp
        cidr: "0.0.0.0/0"
        rule_type: Ingress

#
# This key pair will get injected into /root/.ssh on all hosts.
# ssh private key:
#
ansible_ssh_private_key_file: ~/.ssh/id_rsa

#
# Package install
# 
# Run a full yum update and install packages
#
update_packages: true
common_packages:
#  - python (removed for RHEL8 because python3 was installed in cloud_providers/ec2_infrastructure_deployment.yml)
  - unzip
  - bash-completion
  - tmux
  - wget
  - git
  - vim-enhanced
  - at
  - podman
  - buildah
  - skopeo
