---

- name: populate clair config
  template:
    src: config-template.yaml.j2
    dest: "{{ tmp_dir }}/files/clair-config.yaml"

- name: create clair secret
  command: "{{ openshift_cli }} create secret generic clairsecret --from-file=config.yaml=clair-config.yaml -n {{ quay_project_name }}"
  args:
    chdir: "{{ tmp_dir }}/files"
  ignore_errors: true

- name: enable privileged scc
  command: "{{ openshift_cli }} adm policy add-scc-to-user privileged -z default -n {{ quay_project_name }}"

- name: deploy clair
  command: "{{ openshift_cli }} create -f clair-kubernetes.yml -n {{ quay_project_name }}"
  args:
    chdir: "{{ tmp_dir}}/files"

- name: wait for clair to deploy
  shell:  "{{ openshift_cli }} get pods -n {{ quay_project_name }} | grep clair"
  register: result
  until: result.stdout.find("Running") != -1
  retries: 30
  delay: 10

- name: expose clair route
  command: "{{ openshift_cli }} expose svc/clairsvc -n {{ quay_project_name }}"
