---

- name: create the quay project
  command: "{{ openshift_cli }} new-project {{ quay_project_name }}"

- name: clone the quay operator project
  git:
    repo: https://github.com/redhat-cop/quay-operator.git
    dest: "{{ tmp_dir }}/quay-operator"
    version: v1.0.1
    force: yes

- name: create openshift quay objects
  command: "{{ openshift_cli }} create -f {{ item }}"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"
  with_items:
    - deploy/crds/redhatcop.redhat.io_quayecosystems_crd.yaml
    - deploy/service_account.yaml
    - deploy/cluster_role.yaml
    - deploy/cluster_role_binding.yaml
    - deploy/role.yaml
    - deploy/role_binding.yaml
    - deploy/operator.yaml
  ignore_errors: true

- name: grant admin roles
  command: "{{ openshift_cli }} adm policy add-role-to-user admin system:serviceaccount:{{ quay_project_name }}:quay-operator -n {{ quay_project_name }}"

- name: delete quay limitrange
  command: "{{ openshift_cli }} delete limitrange --all -n {{ quay_project_name }}"
  ignore_errors: true

- name: create redhat pull secret
  command: "{{ openshift_cli }} create secret docker-registry redhat-pull-secret --docker-server=quay.io  --docker-username='{{ quay_pull_user }}' --docker-password='{{ quay_pull_password }}'"

- name: create quay admin password secret
  command: "{{ openshift_cli }} create secret generic quay-admin-password --from-literal=superuser-username={{ quay_admin_user }} --from-literal=superuser-password={{ quay_admin_password }} --from-literal=superuser-email=quay@example.com"

- name: deploy the quay operator
  command: "{{ openshift_cli }} create -f quay_cr.yml"
  args:
    chdir: "{{ tmp_dir}}/files"

- name: wait for quay to deploy
  shell:  "{{ openshift_cli }} get pods -n {{ quay_project_name }} | grep {{ quay_service_name }}"
  register: result
  until: result.stdout.find("Running") != -1
  retries: 30
  delay: 10

- name: create secure route for quay
  command: "{{ openshift_cli }} create route edge quay-secure --service={{ quay_service_name }} -n {{ quay_project_name }}"
  ignore_errors: true
