apiVersion: v1
kind: Template
metadata:
  name: pqc-dev
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: pqc-dev
      app: pqc-dev
    name: pqc-dev
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc.cluster.local:5000/pqc-dev/pqc-dev:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      build: pqc-dev
    name: pqc-dev
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: pqc-dev:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 9T8ahErNKrCufKl0WWd5
      type: GitHub
    - generic:
        secret: nI8ioQAdf5boW7CYnfl6
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: pqc-dev
    name: pqc-dev
  spec:
    replicas: 1
    selector:
      app: pqc-dev
      deploymentconfig: pqc-dev
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: pqc-dev
          deploymentconfig: pqc-dev
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/pqc-dev/pqc-dev:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /rest/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: pqc-dev
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /rest/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pqc-dev
        from:
          kind: ImageStreamTag
          name: pqc-dev:latest
          namespace: pqc-dev
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: pqc-dev
    name: pqc-dev
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: pqc-dev
      deploymentconfig: pqc-dev
    sessionAffinity: None
    type: ClusterIP
